package enums;

public enum Operations {
    LOGIN_CANDIDATE,
    SIGNUP_CANDIDATE,
    LOOKUP_ACCOUNT_CANDIDATE,
    DELETE_ACCOUNT_CANDIDATE,
    LOGOUT_CANDIDATE,
    UPDATE_ACCOUNT_CANDIDATE,
    UNKNOWN,
}
