package enums;

public enum Operations {
    LOGIN_CANDIDATE,
    LOGOUT_CANDIDATE,
    SIGNUP_CANDIDATE,
    LOOKUP_ACCOUNT_CANDIDATE,
    UPDATE_ACCOUNT_CANDIDATE,
    DELETE_ACCOUNT_CANDIDATE,
    LOGIN_RECRUITER,
    LOGOUT_RECRUITER,
    SIGN_UP_RECRUITER,
    LOOKUP_ACCOUNT_RECRUITER,
    UPDATE_ACCOUNT_RECRUITER,
    DELETE_ACCOUNT_RECRUITER,
    INCLUDE_SKILL,
    LOOKUP_SKILL,
    LOOKUP_SKILLSET,
    DELETE_SKILL,
    INCLUDE_JOB,
    INCLUDE_SKILLS,
    DELETE_SKILLSET
}
