package enums;

public enum Statuses {
    SUCCESS,
    ERROR,
    INVALID_LOGIN,
    USER_NOT_FOUND,
    INVALID_EMAIL,
    INVALID_FIELD,
    NULL_RESPONSE,
    USER_EXISTS,
    INVALID_TOKEN,
    SKILL_EXISTS,
    SKILL_NOT_EXISTS,
    SKILL_NOT_FOUND,

}
